name: apk

on:
  push:
    branches:
      - apk
    paths:
      - '.github/workflows/apk.yaml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'sherpa-ncnn/csrc/*'
      - 'sherpa-ncnn/jni/*'
      - 'build-apk.sh'
      - 'build-android-arm64-v8a.sh'
      - 'build-android-armeabi-v7a.sh'
      - 'build-android-x86-64.sh'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/apk.yaml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'sherpa-ncnn/csrc/*'
      - 'sherpa-ncnn/jni/*'
      - 'build-apk.sh'
      - 'build-android-arm64-v8a.sh'
      - 'build-android-armeabi-v7a.sh'
      - 'build-android-x86-64.sh'

concurrency:
  group: apk-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  jni:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Display NDK HOME
        shell: bash
        run: |
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"
          ls -lh ${ANDROID_NDK_LATEST_HOME}

      - name: build APK
        shell: bash
        run: |
          ./build-apk.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./apk/*.apk

      - name: Release APK
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: apks/*.apk
