name: apk

on:
  push:
    branches:
      - master
      - apk
    paths:
      - '.github/workflows/apk.yaml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'sherpa-ncnn/csrc/*'
      - 'sherpa-ncnn/jni/*'
      - '.github/scripts/build-apk.sh'
      - 'build-android-arm64-v8a.sh'
  pull_request:
    branches:
      - master
      - apk
    paths:
      - '.github/workflows/apk.yaml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'sherpa-ncnn/csrc/*'
      - 'sherpa-ncnn/jni/*'
      - '.github/scripts/apk.sh'
      - 'build-android-arm64-v8a.sh'

concurrency:
  group: apk-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  jni:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: nttld/setup-ndk@v1
      #   id: setup-ndk
      #   with:
      #     ndk-version: r21e
      #     local-cache: true
      - name: Display NDK HOME
        shell: bash
        run: |
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"
          ls -lh ${ANDROID_NDK_LATEST_HOME}

      - name: build APK
        shell: bash
        run: |
          ./.github/scripts/build-apk.sh
