name: build-wheels-macos

on:
  push:
    branches:
      - wheel
      - wheel-macos-2023-01-12
    tags:
      - '*'

env:
  SHERPA_NCNN_IS_IN_GITHUB_ACTIONS: 1

concurrency:
  group: build-wheels-macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      # see https://cibuildwheel.readthedocs.io/en/stable/changelog/
      # for a list of versions
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BEFORE_BUILD: "pip install -U cmake numpy"
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_SKIP: "cp27-* cp35-* *-win32 pp* *-musllinux*"
          CIBW_BUILD_VERBOSITY: 3

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

          ls -lh ./wheelhouse/*.whl

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      # - name: Publish wheels to PyPI
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     python3 -m pip install wheel twine setuptools
      #
      #     twine upload ./wheelhouse/*.whl
