name: build-wheels

on:
  push:
    branches:
      - wheel
      - build-wheels-2022-12-30
    tags:
      - '*'

concurrency:
  group: build-wheels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_SKIP: "cp27-* cp35-*"

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

          ls -lh ./wheelhouse/*.whl
