name: dot-net

on:
  push:
    branches:
      - dot-net-all-in-one
    tags:
      - '*'

concurrency:
  group: dot-net-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-libs:
    name: dot-net for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      # see https://cibuildwheel.readthedocs.io/en/stable/changelog/
      # for a list of versions
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BEFORE_BUILD: "pip install -U cmake numpy"
          CIBW_BUILD: "cp38-*64"
          CIBW_SKIP: "cp27-* cp35-* *-win32 pp* *-musllinux*"
          CIBW_BUILD_VERBOSITY: 3

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/*.whl
          unzip -l ./wheelhouse/*.whl


      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-wheels
          path: ./wheelhouse/*.whl

  build-nuget-packages:
    name: build-nuget-packages
    runs-on: ubuntu-latest
    needs: build-libs

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve artifact from ubuntu-latest
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest-wheels
          path: ./

      - name: Retrieve artifact from macos-latest
        uses: actions/download-artifact@v2
        with:
          name: macos-latest-wheels
          path: ./

      - name: Retrieve artifact from windows-latest
        uses: actions/download-artifact@v2
        with:
          name: windows-latest-wheels
          path: ./

      - name: Display wheels
        shell: bash
        run: |
          tree .
